[project]
name = "syncopate"
version = "0.1.0"
description = "An experimental ASGI framework built from the ground up."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typing-extensions>=4.14.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
]
